# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlWindow.ui'
#
# Created: Fri Sep 11 15:52:07 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ControlWindow(object):
    def setupUi(self, ControlWindow):
        ControlWindow.setObjectName(_fromUtf8("ControlWindow"))
        ControlWindow.resize(285, 428)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ControlWindow.sizePolicy().hasHeightForWidth())
        ControlWindow.setSizePolicy(sizePolicy)
        ControlWindow.setMinimumSize(QtCore.QSize(235, 428))
        ControlWindow.setMaximumSize(QtCore.QSize(16777215, 428))
        ControlWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtGui.QWidget(ControlWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.shapes_comboBox = QtGui.QComboBox(self.centralwidget)
        self.shapes_comboBox.setObjectName(_fromUtf8("shapes_comboBox"))
        self.verticalLayout.addWidget(self.shapes_comboBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.filled_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.filled_checkBox.setChecked(True)
        self.filled_checkBox.setObjectName(_fromUtf8("filled_checkBox"))
        self.horizontalLayout_2.addWidget(self.filled_checkBox)
        self.grouped_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.grouped_checkBox.setChecked(True)
        self.grouped_checkBox.setObjectName(_fromUtf8("grouped_checkBox"))
        self.horizontalLayout_2.addWidget(self.grouped_checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.thickness_label = QtGui.QLabel(self.centralwidget)
        self.thickness_label.setObjectName(_fromUtf8("thickness_label"))
        self.verticalLayout_19.addWidget(self.thickness_label)
        self.thickness_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.thickness_spinBox.setMaximum(100)
        self.thickness_spinBox.setProperty("value", 1)
        self.thickness_spinBox.setObjectName(_fromUtf8("thickness_spinBox"))
        self.verticalLayout_19.addWidget(self.thickness_spinBox)
        self.verticalLayout.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.scale_label = QtGui.QLabel(self.centralwidget)
        self.scale_label.setObjectName(_fromUtf8("scale_label"))
        self.verticalLayout_20.addWidget(self.scale_label)
        self.scale_doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.scale_doubleSpinBox.setDecimals(2)
        self.scale_doubleSpinBox.setMaximum(100.0)
        self.scale_doubleSpinBox.setSingleStep(0.01)
        self.scale_doubleSpinBox.setProperty("value", 1.0)
        self.scale_doubleSpinBox.setObjectName(_fromUtf8("scale_doubleSpinBox"))
        self.verticalLayout_20.addWidget(self.scale_doubleSpinBox)
        self.verticalLayout.addLayout(self.verticalLayout_20)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.rotation_label = QtGui.QLabel(self.centralwidget)
        self.rotation_label.setObjectName(_fromUtf8("rotation_label"))
        self.verticalLayout_22.addWidget(self.rotation_label)
        self.rotation_doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.rotation_doubleSpinBox.setEnabled(True)
        self.rotation_doubleSpinBox.setMinimum(-360.0)
        self.rotation_doubleSpinBox.setMaximum(360.0)
        self.rotation_doubleSpinBox.setObjectName(_fromUtf8("rotation_doubleSpinBox"))
        self.verticalLayout_22.addWidget(self.rotation_doubleSpinBox)
        self.verticalLayout.addLayout(self.verticalLayout_22)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.nrows_label = QtGui.QLabel(self.centralwidget)
        self.nrows_label.setEnabled(True)
        self.nrows_label.setObjectName(_fromUtf8("nrows_label"))
        self.verticalLayout_23.addWidget(self.nrows_label)
        self.nrows_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.nrows_spinBox.setEnabled(True)
        self.nrows_spinBox.setMinimum(1)
        self.nrows_spinBox.setMaximum(1000)
        self.nrows_spinBox.setProperty("value", 1)
        self.nrows_spinBox.setObjectName(_fromUtf8("nrows_spinBox"))
        self.verticalLayout_23.addWidget(self.nrows_spinBox)
        self.gridLayout_2.addLayout(self.verticalLayout_23, 0, 0, 1, 1)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.ncolumns_label = QtGui.QLabel(self.centralwidget)
        self.ncolumns_label.setEnabled(True)
        self.ncolumns_label.setObjectName(_fromUtf8("ncolumns_label"))
        self.verticalLayout_24.addWidget(self.ncolumns_label)
        self.ncolumns_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.ncolumns_spinBox.setEnabled(True)
        self.ncolumns_spinBox.setMinimum(1)
        self.ncolumns_spinBox.setMaximum(1000)
        self.ncolumns_spinBox.setObjectName(_fromUtf8("ncolumns_spinBox"))
        self.verticalLayout_24.addWidget(self.ncolumns_spinBox)
        self.gridLayout_2.addLayout(self.verticalLayout_24, 0, 1, 1, 1)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.rowPitch_label = QtGui.QLabel(self.centralwidget)
        self.rowPitch_label.setEnabled(True)
        self.rowPitch_label.setObjectName(_fromUtf8("rowPitch_label"))
        self.verticalLayout_25.addWidget(self.rowPitch_label)
        self.rowPitch_doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.rowPitch_doubleSpinBox.setEnabled(True)
        self.rowPitch_doubleSpinBox.setDecimals(1)
        self.rowPitch_doubleSpinBox.setMaximum(1000.0)
        self.rowPitch_doubleSpinBox.setProperty("value", 100.0)
        self.rowPitch_doubleSpinBox.setObjectName(_fromUtf8("rowPitch_doubleSpinBox"))
        self.verticalLayout_25.addWidget(self.rowPitch_doubleSpinBox)
        self.gridLayout_2.addLayout(self.verticalLayout_25, 1, 0, 1, 1)
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.columnPitch_label = QtGui.QLabel(self.centralwidget)
        self.columnPitch_label.setEnabled(True)
        self.columnPitch_label.setObjectName(_fromUtf8("columnPitch_label"))
        self.verticalLayout_26.addWidget(self.columnPitch_label)
        self.columnPitch_doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.columnPitch_doubleSpinBox.setEnabled(True)
        self.columnPitch_doubleSpinBox.setDecimals(1)
        self.columnPitch_doubleSpinBox.setMaximum(1000.0)
        self.columnPitch_doubleSpinBox.setProperty("value", 100.0)
        self.columnPitch_doubleSpinBox.setObjectName(_fromUtf8("columnPitch_doubleSpinBox"))
        self.verticalLayout_26.addWidget(self.columnPitch_doubleSpinBox)
        self.gridLayout_2.addLayout(self.verticalLayout_26, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        ControlWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ControlWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 285, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuColor = QtGui.QMenu(self.menubar)
        self.menuColor.setObjectName(_fromUtf8("menuColor"))
        ControlWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ControlWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ControlWindow.setStatusBar(self.statusbar)
        self.action_quit = QtGui.QAction(ControlWindow)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_invert = QtGui.QAction(ControlWindow)
        self.action_invert.setCheckable(True)
        self.action_invert.setObjectName(_fromUtf8("action_invert"))
        self.action_reset = QtGui.QAction(ControlWindow)
        self.action_reset.setObjectName(_fromUtf8("action_reset"))
        self.menuFile.addAction(self.action_quit)
        self.menuColor.addAction(self.action_invert)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuColor.menuAction())
        self.thickness_label.setBuddy(self.thickness_spinBox)
        self.scale_label.setBuddy(self.scale_doubleSpinBox)
        self.rotation_label.setBuddy(self.rotation_doubleSpinBox)
        self.nrows_label.setBuddy(self.nrows_spinBox)
        self.ncolumns_label.setBuddy(self.ncolumns_spinBox)
        self.rowPitch_label.setBuddy(self.rowPitch_doubleSpinBox)
        self.columnPitch_label.setBuddy(self.columnPitch_doubleSpinBox)

        self.retranslateUi(ControlWindow)
        QtCore.QObject.connect(self.action_quit, QtCore.SIGNAL(_fromUtf8("activated()")), ControlWindow.close)
        QtCore.QMetaObject.connectSlotsByName(ControlWindow)
        ControlWindow.setTabOrder(self.shapes_comboBox, self.filled_checkBox)
        ControlWindow.setTabOrder(self.filled_checkBox, self.thickness_spinBox)
        ControlWindow.setTabOrder(self.thickness_spinBox, self.scale_doubleSpinBox)
        ControlWindow.setTabOrder(self.scale_doubleSpinBox, self.rotation_doubleSpinBox)
        ControlWindow.setTabOrder(self.rotation_doubleSpinBox, self.nrows_spinBox)
        ControlWindow.setTabOrder(self.nrows_spinBox, self.ncolumns_spinBox)
        ControlWindow.setTabOrder(self.ncolumns_spinBox, self.rowPitch_doubleSpinBox)
        ControlWindow.setTabOrder(self.rowPitch_doubleSpinBox, self.columnPitch_doubleSpinBox)

    def retranslateUi(self, ControlWindow):
        ControlWindow.setWindowTitle(_translate("ControlWindow", "Control window", None))
        self.filled_checkBox.setText(_translate("ControlWindow", "Filled", None))
        self.grouped_checkBox.setText(_translate("ControlWindow", "Grouped", None))
        self.thickness_label.setText(_translate("ControlWindow", "Thickness", None))
        self.scale_label.setText(_translate("ControlWindow", "Scale", None))
        self.rotation_label.setText(_translate("ControlWindow", "Rotation (deg)", None))
        self.nrows_label.setText(_translate("ControlWindow", "Number of rows", None))
        self.ncolumns_label.setText(_translate("ControlWindow", "Number of columns", None))
        self.rowPitch_label.setText(_translate("ControlWindow", "Row pitch", None))
        self.columnPitch_label.setText(_translate("ControlWindow", "Column pitch", None))
        self.menuFile.setTitle(_translate("ControlWindow", "File", None))
        self.menuColor.setTitle(_translate("ControlWindow", "Tools", None))
        self.action_quit.setText(_translate("ControlWindow", "Quit", None))
        self.action_quit.setShortcut(_translate("ControlWindow", "Ctrl+Q", None))
        self.action_invert.setText(_translate("ControlWindow", "Invert", None))
        self.action_invert.setShortcut(_translate("ControlWindow", "Alt+I", None))
        self.action_reset.setText(_translate("ControlWindow", "Reset", None))

